---
title: "AMR_code"
output: html_document
---

### AMR hit
    
```{r}
# Check for presence of data in the AMR dataset
if (dim(amr_resgenes)[1] == 0) {
  num_amr_genes <- 0
} else {
  num_amr_genes <- as.character(nrow(amr_resgenes))
}

renderValueBox({
  valueBox(value = num_amr_genes,
           caption = "Number of AMR genes",
           icon = "fa-pills",
          #  icon="fas fa-capsules",
           color = "warning")
})

```

### Antimicrobial resistance - plot

```{r}
plot <- ggplot(amr_resgenes, aes(x = Subclass, fill = Gene.symbol, label = Gene.symbol)) +
geom_bar() +
geom_text(stat = "count", size = 2, position = position_stack(vjust = 0.5)) +
coord_flip() +
  ylab("Count") +
  xlab("Subclass")
ggplotly(plot)
```

### Antimicrobial resistance - table

```{r}
datatable(amr_resgenes %>%
            select(Class,
                   Subclass,
                   Reference.sequence.length,
                   Accession.of.closest.sequence),
          filter = "top",
          rownames = FALSE,
          colnames = c("Class",
                       "Subclass",
                       "Reference sequence length",
                       "Accession of closest sequence"),
          extensions = list("ColReorder" = NULL,
                            "Buttons" = NULL,
                            "FixedColumns" = list(leftColumns=1)),
          options = list(
            dom = "BRrltpi",
            autoWidth = TRUE,
            columnDefs = list(list(width = "200px", targets = 0)),
            lengthMenu = list(c(10, 50, -1), c("10", "50", "All")),
            ColReorder = TRUE,
            buttons =
              list("copy",
                   list(extend = "collection",
                        buttons = c("csv", "excel", "pdf"),
                        text = "Download"),
                   I("colvis"))))
```